/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 87
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 57
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_EQ = 2,
  anon_sym_patch = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  anon_sym_PIPE = 6,
  anon_sym_phrase = 7,
  anon_sym_COMMA = 8,
  anon_sym_LBRACK = 9,
  anon_sym_RBRACK = 10,
  sym_note = 11,
  sym_rest = 12,
  anon_sym_effect = 13,
  anon_sym_voices = 14,
  anon_sym_mono = 15,
  anon_sym_poly = 16,
  anon_sym_legato = 17,
  anon_sym_DOT_DOT = 18,
  anon_sym_PLUS = 19,
  anon_sym_DASH = 20,
  anon_sym_STAR = 21,
  anon_sym_SLASH = 22,
  sym_identifier = 23,
  sym_number = 24,
  sym_integer = 25,
  sym_source_file = 26,
  sym_declaration = 27,
  sym_patch_decl = 28,
  sym_phrase_decl = 29,
  sym_phrase_call = 30,
  sym_phrase_param_list = 31,
  sym_note_list = 32,
  sym_note_token = 33,
  sym_effect_decl = 34,
  sym_patch_stmt = 35,
  sym_voices_stmt = 36,
  sym_voices_value = 37,
  sym_binding_stmt = 38,
  sym_expr = 39,
  sym_pipe_chain = 40,
  sym_pipe_segment = 41,
  sym_node_call = 42,
  sym_param_list = 43,
  sym_param_item = 44,
  sym_named_param = 45,
  sym_param_value = 46,
  sym_range_literal = 47,
  sym_binary_expr = 48,
  sym_binop = 49,
  sym_primary = 50,
  aux_sym_source_file_repeat1 = 51,
  aux_sym_patch_decl_repeat1 = 52,
  aux_sym_phrase_param_list_repeat1 = 53,
  aux_sym_note_list_repeat1 = 54,
  aux_sym_pipe_chain_repeat1 = 55,
  aux_sym_param_list_repeat1 = 56,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_EQ] = "=",
  [anon_sym_patch] = "patch",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_PIPE] = "|",
  [anon_sym_phrase] = "phrase",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_note] = "note",
  [sym_rest] = "rest",
  [anon_sym_effect] = "effect",
  [anon_sym_voices] = "voices",
  [anon_sym_mono] = "mono",
  [anon_sym_poly] = "poly",
  [anon_sym_legato] = "legato",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_integer] = "integer",
  [sym_source_file] = "source_file",
  [sym_declaration] = "declaration",
  [sym_patch_decl] = "patch_decl",
  [sym_phrase_decl] = "phrase_decl",
  [sym_phrase_call] = "phrase_call",
  [sym_phrase_param_list] = "phrase_param_list",
  [sym_note_list] = "note_list",
  [sym_note_token] = "note_token",
  [sym_effect_decl] = "effect_decl",
  [sym_patch_stmt] = "patch_stmt",
  [sym_voices_stmt] = "voices_stmt",
  [sym_voices_value] = "voices_value",
  [sym_binding_stmt] = "binding_stmt",
  [sym_expr] = "expr",
  [sym_pipe_chain] = "pipe_chain",
  [sym_pipe_segment] = "pipe_segment",
  [sym_node_call] = "node_call",
  [sym_param_list] = "param_list",
  [sym_param_item] = "param_item",
  [sym_named_param] = "named_param",
  [sym_param_value] = "param_value",
  [sym_range_literal] = "range_literal",
  [sym_binary_expr] = "binary_expr",
  [sym_binop] = "binop",
  [sym_primary] = "primary",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_patch_decl_repeat1] = "patch_decl_repeat1",
  [aux_sym_phrase_param_list_repeat1] = "phrase_param_list_repeat1",
  [aux_sym_note_list_repeat1] = "note_list_repeat1",
  [aux_sym_pipe_chain_repeat1] = "pipe_chain_repeat1",
  [aux_sym_param_list_repeat1] = "param_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_patch] = anon_sym_patch,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_phrase] = anon_sym_phrase,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_note] = sym_note,
  [sym_rest] = sym_rest,
  [anon_sym_effect] = anon_sym_effect,
  [anon_sym_voices] = anon_sym_voices,
  [anon_sym_mono] = anon_sym_mono,
  [anon_sym_poly] = anon_sym_poly,
  [anon_sym_legato] = anon_sym_legato,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_integer] = sym_integer,
  [sym_source_file] = sym_source_file,
  [sym_declaration] = sym_declaration,
  [sym_patch_decl] = sym_patch_decl,
  [sym_phrase_decl] = sym_phrase_decl,
  [sym_phrase_call] = sym_phrase_call,
  [sym_phrase_param_list] = sym_phrase_param_list,
  [sym_note_list] = sym_note_list,
  [sym_note_token] = sym_note_token,
  [sym_effect_decl] = sym_effect_decl,
  [sym_patch_stmt] = sym_patch_stmt,
  [sym_voices_stmt] = sym_voices_stmt,
  [sym_voices_value] = sym_voices_value,
  [sym_binding_stmt] = sym_binding_stmt,
  [sym_expr] = sym_expr,
  [sym_pipe_chain] = sym_pipe_chain,
  [sym_pipe_segment] = sym_pipe_segment,
  [sym_node_call] = sym_node_call,
  [sym_param_list] = sym_param_list,
  [sym_param_item] = sym_param_item,
  [sym_named_param] = sym_named_param,
  [sym_param_value] = sym_param_value,
  [sym_range_literal] = sym_range_literal,
  [sym_binary_expr] = sym_binary_expr,
  [sym_binop] = sym_binop,
  [sym_primary] = sym_primary,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_patch_decl_repeat1] = aux_sym_patch_decl_repeat1,
  [aux_sym_phrase_param_list_repeat1] = aux_sym_phrase_param_list_repeat1,
  [aux_sym_note_list_repeat1] = aux_sym_note_list_repeat1,
  [aux_sym_pipe_chain_repeat1] = aux_sym_pipe_chain_repeat1,
  [aux_sym_param_list_repeat1] = aux_sym_param_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_patch] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_phrase] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_note] = {
    .visible = true,
    .named = true,
  },
  [sym_rest] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_effect] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_voices] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mono] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_poly] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_legato] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_patch_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_phrase_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_phrase_call] = {
    .visible = true,
    .named = true,
  },
  [sym_phrase_param_list] = {
    .visible = true,
    .named = true,
  },
  [sym_note_list] = {
    .visible = true,
    .named = true,
  },
  [sym_note_token] = {
    .visible = true,
    .named = true,
  },
  [sym_effect_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_patch_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_voices_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_voices_value] = {
    .visible = true,
    .named = true,
  },
  [sym_binding_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_pipe_chain] = {
    .visible = true,
    .named = true,
  },
  [sym_pipe_segment] = {
    .visible = true,
    .named = true,
  },
  [sym_node_call] = {
    .visible = true,
    .named = true,
  },
  [sym_param_list] = {
    .visible = true,
    .named = true,
  },
  [sym_param_item] = {
    .visible = true,
    .named = true,
  },
  [sym_named_param] = {
    .visible = true,
    .named = true,
  },
  [sym_param_value] = {
    .visible = true,
    .named = true,
  },
  [sym_range_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binop] = {
    .visible = true,
    .named = true,
  },
  [sym_primary] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_patch_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_phrase_param_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_note_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pipe_chain_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_param_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_hi = 1,
  field_key = 2,
  field_kind = 3,
  field_left = 4,
  field_lo = 5,
  field_name = 6,
  field_op = 7,
  field_patch = 8,
  field_right = 9,
  field_value = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_hi] = "hi",
  [field_key] = "key",
  [field_kind] = "kind",
  [field_left] = "left",
  [field_lo] = "lo",
  [field_name] = "name",
  [field_op] = "op",
  [field_patch] = "patch",
  [field_right] = "right",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 3},
  [7] = {.index = 11, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_name, 0},
    {field_patch, 4},
  [3] =
    {field_name, 0},
    {field_value, 2},
  [5] =
    {field_kind, 0},
  [6] =
    {field_key, 0},
    {field_value, 2},
  [8] =
    {field_left, 0},
    {field_op, 1},
    {field_right, 2},
  [11] =
    {field_hi, 2},
    {field_lo, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(39);
      ADVANCE_MAP(
        '*', 64,
        '+', 62,
        ',', 47,
        '-', 63,
        '.', 2,
        '/', 65,
        '=', 41,
        '[', 48,
        ']', 49,
        '_', 53,
        'l', 13,
        'm', 24,
        'p', 7,
        'v', 25,
        '{', 43,
        '|', 45,
        '}', 44,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('a' <= lookahead && lookahead <= 'g')) ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(77);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '*', 64,
        '+', 62,
        ',', 47,
        '-', 63,
        '/', 65,
        '[', 48,
        'v', 72,
        '{', 43,
        '|', 45,
        '}', 44,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(80);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 2:
      if (lookahead == '.') ADVANCE(61);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(40);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == 'e') ADVANCE(17);
      if (lookahead == 'p') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == 'l') ADVANCE(69);
      if (lookahead == 'v') ADVANCE(72);
      if (lookahead == '}') ADVANCE(44);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(31);
      if (lookahead == 'h') ADVANCE(28);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(31);
      if (lookahead == 'h') ADVANCE(28);
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(33);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(20);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'c') ADVANCE(32);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 17:
      if (lookahead == 'f') ADVANCE(18);
      END_STATE();
    case 18:
      if (lookahead == 'f') ADVANCE(16);
      END_STATE();
    case 19:
      if (lookahead == 'g') ADVANCE(9);
      END_STATE();
    case 20:
      if (lookahead == 'h') ADVANCE(42);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(11);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(34);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 26:
      if (lookahead == 'o') ADVANCE(57);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(59);
      END_STATE();
    case 28:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 29:
      if (lookahead == 's') ADVANCE(55);
      END_STATE();
    case 30:
      if (lookahead == 's') ADVANCE(14);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(54);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 34:
      if (lookahead == 'y') ADVANCE(58);
      END_STATE();
    case 35:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      END_STATE();
    case 38:
      if (eof) ADVANCE(39);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '[') ADVANCE(48);
      if (lookahead == '}') ADVANCE(44);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(38);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(77);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_patch);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_phrase);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_note);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_note);
      if (lookahead == '#' ||
          lookahead == 'b') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '8')) ADVANCE(50);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_note);
      if (('0' <= lookahead && lookahead <= '8')) ADVANCE(50);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_rest);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_effect);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_voices);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_voices);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_mono);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_poly);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_legato);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_legato);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(40);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(36);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(80);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 38},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 38},
  [11] = {.lex_state = 38},
  [12] = {.lex_state = 38},
  [13] = {.lex_state = 38},
  [14] = {.lex_state = 38},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 38},
  [18] = {.lex_state = 38},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 38},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 38},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 38},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 38},
  [37] = {.lex_state = 38},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 38},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 38},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 38},
  [57] = {.lex_state = 38},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 38},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 38},
  [64] = {.lex_state = 38},
  [65] = {.lex_state = 38},
  [66] = {.lex_state = 38},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 38},
  [80] = {.lex_state = 38},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_patch] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_phrase] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_note] = ACTIONS(1),
    [sym_rest] = ACTIONS(1),
    [anon_sym_voices] = ACTIONS(1),
    [anon_sym_mono] = ACTIONS(1),
    [anon_sym_poly] = ACTIONS(1),
    [anon_sym_legato] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(85),
    [sym_declaration] = STATE(14),
    [sym_patch_decl] = STATE(65),
    [sym_phrase_decl] = STATE(65),
    [sym_effect_decl] = STATE(65),
    [aux_sym_source_file_repeat1] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 3,
      anon_sym_voices,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(11), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [20] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_RBRACE,
    ACTIONS(17), 1,
      anon_sym_voices,
    ACTIONS(19), 1,
      sym_identifier,
    STATE(19), 1,
      sym_node_call,
    STATE(6), 2,
      sym_patch_stmt,
      aux_sym_patch_decl_repeat1,
    STATE(39), 3,
      sym_voices_stmt,
      sym_binding_stmt,
      sym_pipe_chain,
  [45] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 3,
      anon_sym_voices,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(11), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [62] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_voices,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_RBRACE,
    STATE(19), 1,
      sym_node_call,
    STATE(3), 2,
      sym_patch_stmt,
      aux_sym_patch_decl_repeat1,
    STATE(39), 3,
      sym_voices_stmt,
      sym_binding_stmt,
      sym_pipe_chain,
  [87] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_RBRACE,
    ACTIONS(25), 1,
      anon_sym_voices,
    ACTIONS(28), 1,
      sym_identifier,
    STATE(19), 1,
      sym_node_call,
    STATE(6), 2,
      sym_patch_stmt,
      aux_sym_patch_decl_repeat1,
    STATE(39), 3,
      sym_voices_stmt,
      sym_binding_stmt,
      sym_pipe_chain,
  [112] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_SLASH,
    ACTIONS(31), 1,
      anon_sym_DOT_DOT,
    ACTIONS(11), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [130] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    STATE(50), 1,
      sym_binop,
    ACTIONS(35), 2,
      anon_sym_voices,
      sym_identifier,
    ACTIONS(37), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [152] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      anon_sym_SLASH,
    STATE(50), 1,
      sym_binop,
    ACTIONS(37), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
    ACTIONS(41), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [172] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(45), 1,
      sym_number,
    STATE(8), 1,
      sym_primary,
    STATE(19), 1,
      sym_node_call,
    STATE(40), 1,
      sym_expr,
    STATE(41), 2,
      sym_pipe_chain,
      sym_binary_expr,
  [195] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(47), 1,
      sym_number,
    STATE(9), 1,
      sym_primary,
    STATE(46), 1,
      sym_param_value,
    STATE(45), 3,
      sym_node_call,
      sym_range_literal,
      sym_binary_expr,
  [216] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 1,
      sym_identifier,
    STATE(12), 2,
      sym_declaration,
      aux_sym_source_file_repeat1,
    STATE(65), 3,
      sym_patch_decl,
      sym_phrase_decl,
      sym_effect_decl,
  [235] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      sym_number,
    ACTIONS(54), 1,
      anon_sym_RBRACE,
    ACTIONS(56), 1,
      sym_identifier,
    STATE(43), 1,
      sym_param_item,
    STATE(86), 1,
      sym_param_list,
    STATE(55), 2,
      sym_named_param,
      sym_primary,
  [258] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
    STATE(12), 2,
      sym_declaration,
      aux_sym_source_file_repeat1,
    STATE(65), 3,
      sym_patch_decl,
      sym_phrase_decl,
      sym_effect_decl,
  [277] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 2,
      anon_sym_voices,
      sym_identifier,
    ACTIONS(60), 4,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [291] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 2,
      anon_sym_voices,
      sym_identifier,
    ACTIONS(64), 4,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [305] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      sym_number,
    ACTIONS(56), 1,
      sym_identifier,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
    STATE(61), 1,
      sym_param_item,
    STATE(55), 2,
      sym_named_param,
      sym_primary,
  [325] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      sym_number,
    ACTIONS(56), 1,
      sym_identifier,
    ACTIONS(70), 1,
      anon_sym_RBRACE,
    STATE(61), 1,
      sym_param_item,
    STATE(55), 2,
      sym_named_param,
      sym_primary,
  [345] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      anon_sym_RBRACE,
    ACTIONS(74), 1,
      anon_sym_PIPE,
    STATE(20), 1,
      aux_sym_pipe_chain_repeat1,
    ACTIONS(76), 2,
      anon_sym_voices,
      sym_identifier,
  [362] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_PIPE,
    ACTIONS(78), 1,
      anon_sym_RBRACE,
    STATE(21), 1,
      aux_sym_pipe_chain_repeat1,
    ACTIONS(80), 2,
      anon_sym_voices,
      sym_identifier,
  [379] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_RBRACE,
    ACTIONS(84), 1,
      anon_sym_PIPE,
    STATE(21), 1,
      aux_sym_pipe_chain_repeat1,
    ACTIONS(87), 2,
      anon_sym_voices,
      sym_identifier,
  [396] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      anon_sym_LBRACK,
    ACTIONS(91), 1,
      sym_identifier,
    STATE(44), 1,
      sym_named_param,
    STATE(58), 1,
      sym_phrase_param_list,
    STATE(71), 1,
      sym_note_list,
  [415] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(93), 2,
      anon_sym_RBRACE,
      anon_sym_PIPE,
    ACTIONS(95), 2,
      anon_sym_voices,
      sym_identifier,
  [430] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_RBRACK,
    ACTIONS(99), 2,
      sym_note,
      sym_rest,
    STATE(26), 2,
      sym_note_token,
      aux_sym_note_list_repeat1,
  [445] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_RBRACK,
    ACTIONS(103), 2,
      sym_note,
      sym_rest,
    STATE(25), 2,
      sym_note_token,
      aux_sym_note_list_repeat1,
  [460] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      anon_sym_RBRACK,
    ACTIONS(99), 2,
      sym_note,
      sym_rest,
    STATE(25), 2,
      sym_note_token,
      aux_sym_note_list_repeat1,
  [475] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 2,
      anon_sym_voices,
      sym_identifier,
    ACTIONS(108), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [488] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      sym_number,
    ACTIONS(56), 1,
      sym_identifier,
    STATE(61), 1,
      sym_param_item,
    STATE(55), 2,
      sym_named_param,
      sym_primary,
  [505] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 2,
      anon_sym_RBRACE,
      anon_sym_PIPE,
    ACTIONS(95), 2,
      anon_sym_voices,
      sym_identifier,
  [517] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 2,
      anon_sym_RBRACE,
      anon_sym_PIPE,
    ACTIONS(87), 2,
      anon_sym_voices,
      sym_identifier,
  [529] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      anon_sym_patch,
    ACTIONS(114), 1,
      anon_sym_phrase,
    ACTIONS(116), 1,
      anon_sym_effect,
    STATE(83), 1,
      sym_phrase_call,
  [545] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      anon_sym_RBRACE,
    ACTIONS(122), 1,
      anon_sym_legato,
    ACTIONS(120), 2,
      anon_sym_voices,
      sym_identifier,
  [559] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      anon_sym_COMMA,
    ACTIONS(126), 1,
      anon_sym_LBRACK,
    STATE(48), 1,
      aux_sym_phrase_param_list_repeat1,
  [572] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 1,
      sym_identifier,
    STATE(29), 1,
      sym_node_call,
    STATE(30), 1,
      sym_pipe_segment,
  [585] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 3,
      anon_sym_RBRACK,
      sym_note,
      sym_rest,
  [594] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(19), 1,
      sym_node_call,
    STATE(75), 1,
      sym_pipe_chain,
  [607] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(126), 1,
      anon_sym_LBRACK,
    STATE(60), 1,
      sym_named_param,
  [620] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      anon_sym_RBRACE,
    ACTIONS(136), 2,
      anon_sym_voices,
      sym_identifier,
  [631] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_RBRACE,
    ACTIONS(140), 2,
      anon_sym_voices,
      sym_identifier,
  [642] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_RBRACE,
    ACTIONS(144), 2,
      anon_sym_voices,
      sym_identifier,
  [653] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    ACTIONS(35), 2,
      anon_sym_voices,
      sym_identifier,
  [664] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      anon_sym_EQ,
    ACTIONS(11), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [675] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      anon_sym_RBRACE,
    ACTIONS(150), 1,
      anon_sym_COMMA,
    STATE(52), 1,
      aux_sym_param_list_repeat1,
  [688] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_COMMA,
    ACTIONS(154), 1,
      anon_sym_LBRACK,
    STATE(33), 1,
      aux_sym_phrase_param_list_repeat1,
  [701] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [710] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [719] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(158), 1,
      anon_sym_LBRACK,
    STATE(60), 1,
      sym_named_param,
  [732] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      anon_sym_COMMA,
    ACTIONS(163), 1,
      anon_sym_LBRACK,
    STATE(48), 1,
      aux_sym_phrase_param_list_repeat1,
  [745] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_RBRACE,
    ACTIONS(167), 2,
      anon_sym_voices,
      sym_identifier,
  [756] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(27), 1,
      sym_primary,
    ACTIONS(45), 2,
      sym_identifier,
      sym_number,
  [767] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_mono,
    ACTIONS(171), 1,
      anon_sym_poly,
    STATE(38), 1,
      sym_voices_value,
  [780] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    STATE(53), 1,
      aux_sym_param_list_repeat1,
  [793] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_RBRACE,
    ACTIONS(177), 1,
      anon_sym_COMMA,
    STATE(53), 1,
      aux_sym_param_list_repeat1,
  [806] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [815] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [823] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [831] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [839] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      anon_sym_LBRACK,
    STATE(82), 1,
      sym_note_list,
  [849] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [857] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 2,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [865] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [873] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(190), 1,
      anon_sym_EQ,
  [883] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      sym_identifier,
    STATE(60), 1,
      sym_named_param,
  [893] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 2,
      sym_identifier,
      sym_number,
  [901] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [909] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [917] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      anon_sym_EQ,
  [924] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      anon_sym_EQ,
  [931] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_LBRACE,
  [938] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      anon_sym_RBRACE,
  [945] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      anon_sym_RBRACE,
  [952] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
  [959] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_EQ,
  [966] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      sym_integer,
  [973] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_RBRACE,
  [980] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_PIPE,
  [987] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_PIPE,
  [994] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_RBRACE,
  [1001] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 1,
      sym_number,
  [1008] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      sym_identifier,
  [1015] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_LBRACE,
  [1022] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      anon_sym_RBRACE,
  [1029] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_PIPE,
  [1036] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      anon_sym_LBRACE,
  [1043] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      ts_builtin_sym_end,
  [1050] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 20,
  [SMALL_STATE(4)] = 45,
  [SMALL_STATE(5)] = 62,
  [SMALL_STATE(6)] = 87,
  [SMALL_STATE(7)] = 112,
  [SMALL_STATE(8)] = 130,
  [SMALL_STATE(9)] = 152,
  [SMALL_STATE(10)] = 172,
  [SMALL_STATE(11)] = 195,
  [SMALL_STATE(12)] = 216,
  [SMALL_STATE(13)] = 235,
  [SMALL_STATE(14)] = 258,
  [SMALL_STATE(15)] = 277,
  [SMALL_STATE(16)] = 291,
  [SMALL_STATE(17)] = 305,
  [SMALL_STATE(18)] = 325,
  [SMALL_STATE(19)] = 345,
  [SMALL_STATE(20)] = 362,
  [SMALL_STATE(21)] = 379,
  [SMALL_STATE(22)] = 396,
  [SMALL_STATE(23)] = 415,
  [SMALL_STATE(24)] = 430,
  [SMALL_STATE(25)] = 445,
  [SMALL_STATE(26)] = 460,
  [SMALL_STATE(27)] = 475,
  [SMALL_STATE(28)] = 488,
  [SMALL_STATE(29)] = 505,
  [SMALL_STATE(30)] = 517,
  [SMALL_STATE(31)] = 529,
  [SMALL_STATE(32)] = 545,
  [SMALL_STATE(33)] = 559,
  [SMALL_STATE(34)] = 572,
  [SMALL_STATE(35)] = 585,
  [SMALL_STATE(36)] = 594,
  [SMALL_STATE(37)] = 607,
  [SMALL_STATE(38)] = 620,
  [SMALL_STATE(39)] = 631,
  [SMALL_STATE(40)] = 642,
  [SMALL_STATE(41)] = 653,
  [SMALL_STATE(42)] = 664,
  [SMALL_STATE(43)] = 675,
  [SMALL_STATE(44)] = 688,
  [SMALL_STATE(45)] = 701,
  [SMALL_STATE(46)] = 710,
  [SMALL_STATE(47)] = 719,
  [SMALL_STATE(48)] = 732,
  [SMALL_STATE(49)] = 745,
  [SMALL_STATE(50)] = 756,
  [SMALL_STATE(51)] = 767,
  [SMALL_STATE(52)] = 780,
  [SMALL_STATE(53)] = 793,
  [SMALL_STATE(54)] = 806,
  [SMALL_STATE(55)] = 815,
  [SMALL_STATE(56)] = 823,
  [SMALL_STATE(57)] = 831,
  [SMALL_STATE(58)] = 839,
  [SMALL_STATE(59)] = 849,
  [SMALL_STATE(60)] = 857,
  [SMALL_STATE(61)] = 865,
  [SMALL_STATE(62)] = 873,
  [SMALL_STATE(63)] = 883,
  [SMALL_STATE(64)] = 893,
  [SMALL_STATE(65)] = 901,
  [SMALL_STATE(66)] = 909,
  [SMALL_STATE(67)] = 917,
  [SMALL_STATE(68)] = 924,
  [SMALL_STATE(69)] = 931,
  [SMALL_STATE(70)] = 938,
  [SMALL_STATE(71)] = 945,
  [SMALL_STATE(72)] = 952,
  [SMALL_STATE(73)] = 959,
  [SMALL_STATE(74)] = 966,
  [SMALL_STATE(75)] = 973,
  [SMALL_STATE(76)] = 980,
  [SMALL_STATE(77)] = 987,
  [SMALL_STATE(78)] = 994,
  [SMALL_STATE(79)] = 1001,
  [SMALL_STATE(80)] = 1008,
  [SMALL_STATE(81)] = 1015,
  [SMALL_STATE(82)] = 1022,
  [SMALL_STATE(83)] = 1029,
  [SMALL_STATE(84)] = 1036,
  [SMALL_STATE(85)] = 1043,
  [SMALL_STATE(86)] = 1050,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primary, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_patch_decl_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_patch_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_patch_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_value, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_call, 4, 0, 4),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node_call, 4, 0, 4),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_call, 3, 0, 4),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node_call, 3, 0, 4),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_list, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_list, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipe_chain, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pipe_chain, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipe_chain, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pipe_chain, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pipe_chain_repeat1, 2, 0, 0),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pipe_chain_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pipe_chain_repeat1, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipe_segment, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pipe_segment, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_note_list_repeat1, 2, 0, 0),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_note_list_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expr, 3, 0, 6),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expr, 3, 0, 6),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_voices_value, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_voices_value, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_phrase_param_list, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_token, 1, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_voices_stmt, 3, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_voices_stmt, 3, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_patch_stmt, 1, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_patch_stmt, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binding_stmt, 3, 0, 3),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binding_stmt, 3, 0, 3),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_list, 1, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_phrase_param_list, 1, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_param, 3, 0, 5),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_phrase_param_list, 3, 0, 0),
  [160] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_phrase_param_list_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_phrase_param_list_repeat1, 2, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_voices_value, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_voices_value, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_param_list_repeat1, 2, 0, 0),
  [177] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_param_list_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range_literal, 3, 0, 7),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_item, 1, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_patch_decl, 6, 0, 1),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_patch_decl, 5, 0, 1),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_effect_decl, 6, 0, 1),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binop, 1, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 1, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_phrase_decl, 5, 0, 2),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_list, 3, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_phrase_call, 5, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_phrase_call, 4, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_list, 2, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [230] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_patchlang(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
