/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 60
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_EQ = 2,
  anon_sym_patch = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  anon_sym_effect = 6,
  anon_sym_voices = 7,
  anon_sym_mono = 8,
  anon_sym_poly = 9,
  anon_sym_legato = 10,
  anon_sym_PIPE = 11,
  anon_sym_COMMA = 12,
  anon_sym_PLUS = 13,
  anon_sym_DASH = 14,
  anon_sym_STAR = 15,
  anon_sym_SLASH = 16,
  sym_identifier = 17,
  sym_number = 18,
  sym_integer = 19,
  sym_source_file = 20,
  sym_declaration = 21,
  sym_patch_decl = 22,
  sym_effect_decl = 23,
  sym_patch_stmt = 24,
  sym_voices_stmt = 25,
  sym_voices_value = 26,
  sym_binding_stmt = 27,
  sym_expr = 28,
  sym_pipe_chain = 29,
  sym_pipe_segment = 30,
  sym_node_call = 31,
  sym_param_list = 32,
  sym_param_item = 33,
  sym_named_param = 34,
  sym_param_value = 35,
  sym_binary_expr = 36,
  sym_binop = 37,
  sym_primary = 38,
  aux_sym_source_file_repeat1 = 39,
  aux_sym_patch_decl_repeat1 = 40,
  aux_sym_pipe_chain_repeat1 = 41,
  aux_sym_param_list_repeat1 = 42,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_EQ] = "=",
  [anon_sym_patch] = "patch",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_effect] = "effect",
  [anon_sym_voices] = "voices",
  [anon_sym_mono] = "mono",
  [anon_sym_poly] = "poly",
  [anon_sym_legato] = "legato",
  [anon_sym_PIPE] = "|",
  [anon_sym_COMMA] = ",",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_integer] = "integer",
  [sym_source_file] = "source_file",
  [sym_declaration] = "declaration",
  [sym_patch_decl] = "patch_decl",
  [sym_effect_decl] = "effect_decl",
  [sym_patch_stmt] = "patch_stmt",
  [sym_voices_stmt] = "voices_stmt",
  [sym_voices_value] = "voices_value",
  [sym_binding_stmt] = "binding_stmt",
  [sym_expr] = "expr",
  [sym_pipe_chain] = "pipe_chain",
  [sym_pipe_segment] = "pipe_segment",
  [sym_node_call] = "node_call",
  [sym_param_list] = "param_list",
  [sym_param_item] = "param_item",
  [sym_named_param] = "named_param",
  [sym_param_value] = "param_value",
  [sym_binary_expr] = "binary_expr",
  [sym_binop] = "binop",
  [sym_primary] = "primary",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_patch_decl_repeat1] = "patch_decl_repeat1",
  [aux_sym_pipe_chain_repeat1] = "pipe_chain_repeat1",
  [aux_sym_param_list_repeat1] = "param_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_patch] = anon_sym_patch,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_effect] = anon_sym_effect,
  [anon_sym_voices] = anon_sym_voices,
  [anon_sym_mono] = anon_sym_mono,
  [anon_sym_poly] = anon_sym_poly,
  [anon_sym_legato] = anon_sym_legato,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_integer] = sym_integer,
  [sym_source_file] = sym_source_file,
  [sym_declaration] = sym_declaration,
  [sym_patch_decl] = sym_patch_decl,
  [sym_effect_decl] = sym_effect_decl,
  [sym_patch_stmt] = sym_patch_stmt,
  [sym_voices_stmt] = sym_voices_stmt,
  [sym_voices_value] = sym_voices_value,
  [sym_binding_stmt] = sym_binding_stmt,
  [sym_expr] = sym_expr,
  [sym_pipe_chain] = sym_pipe_chain,
  [sym_pipe_segment] = sym_pipe_segment,
  [sym_node_call] = sym_node_call,
  [sym_param_list] = sym_param_list,
  [sym_param_item] = sym_param_item,
  [sym_named_param] = sym_named_param,
  [sym_param_value] = sym_param_value,
  [sym_binary_expr] = sym_binary_expr,
  [sym_binop] = sym_binop,
  [sym_primary] = sym_primary,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_patch_decl_repeat1] = aux_sym_patch_decl_repeat1,
  [aux_sym_pipe_chain_repeat1] = aux_sym_pipe_chain_repeat1,
  [aux_sym_param_list_repeat1] = aux_sym_param_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_patch] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_effect] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_voices] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mono] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_poly] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_legato] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_patch_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_effect_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_patch_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_voices_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_voices_value] = {
    .visible = true,
    .named = true,
  },
  [sym_binding_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_pipe_chain] = {
    .visible = true,
    .named = true,
  },
  [sym_pipe_segment] = {
    .visible = true,
    .named = true,
  },
  [sym_node_call] = {
    .visible = true,
    .named = true,
  },
  [sym_param_list] = {
    .visible = true,
    .named = true,
  },
  [sym_param_item] = {
    .visible = true,
    .named = true,
  },
  [sym_named_param] = {
    .visible = true,
    .named = true,
  },
  [sym_param_value] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binop] = {
    .visible = true,
    .named = true,
  },
  [sym_primary] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_patch_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pipe_chain_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_param_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_kind = 2,
  field_left = 3,
  field_name = 4,
  field_op = 5,
  field_right = 6,
  field_value = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_kind] = "kind",
  [field_left] = "left",
  [field_name] = "name",
  [field_op] = "op",
  [field_right] = "right",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 3},
  [5] = {.index = 7, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_name, 0},
    {field_value, 2},
  [3] =
    {field_kind, 0},
  [4] =
    {field_left, 0},
    {field_op, 1},
    {field_right, 2},
  [7] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        '#', 32,
        '*', 48,
        '+', 46,
        ',', 45,
        '-', 47,
        '/', 49,
        '=', 33,
        'e', 11,
        'l', 8,
        'm', 18,
        'p', 3,
        'v', 19,
        '{', 35,
        '|', 44,
        '}', 36,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '#', 32,
        '*', 48,
        '+', 46,
        ',', 45,
        '-', 47,
        '/', 49,
        'v', 56,
        '{', 35,
        '|', 44,
        '}', 36,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(32);
      if (lookahead == 'l') ADVANCE(53);
      if (lookahead == 'v') ADVANCE(56);
      if (lookahead == '}') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(23);
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(25);
      END_STATE();
    case 5:
      if (lookahead == 'c') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == 'c') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 11:
      if (lookahead == 'f') ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == 'f') ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == 'g') ADVANCE(4);
      END_STATE();
    case 14:
      if (lookahead == 'h') ADVANCE(34);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(6);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(42);
      END_STATE();
    case 22:
      if (lookahead == 's') ADVANCE(38);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(5);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(21);
      END_STATE();
    case 26:
      if (lookahead == 'y') ADVANCE(41);
      END_STATE();
    case 27:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 30:
      if (eof) ADVANCE(31);
      if (lookahead == '#') ADVANCE(32);
      if (lookahead == '}') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_patch);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_effect);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_voices);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_voices);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_mono);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_poly);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_legato);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_legato);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(28);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 30},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 30},
  [9] = {.lex_state = 30},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 30},
  [12] = {.lex_state = 30},
  [13] = {.lex_state = 30},
  [14] = {.lex_state = 30},
  [15] = {.lex_state = 30},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 30},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 30},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 30},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 30},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 30},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 30},
  [44] = {.lex_state = 30},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 30},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 30},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_patch] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_effect] = ACTIONS(1),
    [anon_sym_voices] = ACTIONS(1),
    [anon_sym_mono] = ACTIONS(1),
    [anon_sym_poly] = ACTIONS(1),
    [anon_sym_legato] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(56),
    [sym_declaration] = STATE(12),
    [sym_patch_decl] = STATE(41),
    [sym_effect_decl] = STATE(41),
    [aux_sym_source_file_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_RBRACE,
    ACTIONS(11), 1,
      anon_sym_voices,
    ACTIONS(13), 1,
      sym_identifier,
    STATE(22), 1,
      sym_node_call,
    STATE(4), 2,
      sym_patch_stmt,
      aux_sym_patch_decl_repeat1,
    STATE(34), 3,
      sym_voices_stmt,
      sym_binding_stmt,
      sym_pipe_chain,
  [25] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 2,
      anon_sym_voices,
      sym_identifier,
    ACTIONS(17), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [44] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_voices,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_RBRACE,
    STATE(22), 1,
      sym_node_call,
    STATE(5), 2,
      sym_patch_stmt,
      aux_sym_patch_decl_repeat1,
    STATE(34), 3,
      sym_voices_stmt,
      sym_binding_stmt,
      sym_pipe_chain,
  [69] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_RBRACE,
    ACTIONS(25), 1,
      anon_sym_voices,
    ACTIONS(28), 1,
      sym_identifier,
    STATE(22), 1,
      sym_node_call,
    STATE(5), 2,
      sym_patch_stmt,
      aux_sym_patch_decl_repeat1,
    STATE(34), 3,
      sym_voices_stmt,
      sym_binding_stmt,
      sym_pipe_chain,
  [94] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 2,
      anon_sym_voices,
      sym_identifier,
    ACTIONS(17), 6,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [110] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    STATE(36), 1,
      sym_binop,
    ACTIONS(33), 2,
      anon_sym_voices,
      sym_identifier,
    ACTIONS(35), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [130] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      sym_identifier,
    ACTIONS(39), 1,
      sym_number,
    STATE(7), 1,
      sym_primary,
    STATE(22), 1,
      sym_node_call,
    STATE(32), 1,
      sym_expr,
    STATE(29), 2,
      sym_pipe_chain,
      sym_binary_expr,
  [153] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      sym_number,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    ACTIONS(43), 1,
      sym_identifier,
    STATE(28), 1,
      sym_param_item,
    STATE(53), 1,
      sym_param_list,
    STATE(40), 2,
      sym_named_param,
      sym_primary,
  [176] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(36), 1,
      sym_binop,
    ACTIONS(45), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
    ACTIONS(35), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [193] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(49), 1,
      sym_identifier,
    STATE(11), 2,
      sym_declaration,
      aux_sym_source_file_repeat1,
    STATE(41), 2,
      sym_patch_decl,
      sym_effect_decl,
  [211] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    STATE(11), 2,
      sym_declaration,
      aux_sym_source_file_repeat1,
    STATE(41), 2,
      sym_patch_decl,
      sym_effect_decl,
  [229] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      sym_identifier,
    ACTIONS(39), 1,
      sym_number,
    STATE(10), 1,
      sym_primary,
    STATE(47), 1,
      sym_param_value,
    STATE(48), 2,
      sym_node_call,
      sym_binary_expr,
  [249] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      sym_number,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(54), 1,
      anon_sym_RBRACE,
    STATE(49), 1,
      sym_param_item,
    STATE(40), 2,
      sym_named_param,
      sym_primary,
  [269] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      sym_number,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(56), 1,
      anon_sym_RBRACE,
    STATE(49), 1,
      sym_param_item,
    STATE(40), 2,
      sym_named_param,
      sym_primary,
  [289] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 2,
      anon_sym_voices,
      sym_identifier,
    ACTIONS(58), 3,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [302] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      sym_number,
    ACTIONS(43), 1,
      sym_identifier,
    STATE(49), 1,
      sym_param_item,
    STATE(40), 2,
      sym_named_param,
      sym_primary,
  [319] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_RBRACE,
    ACTIONS(66), 1,
      anon_sym_PIPE,
    STATE(21), 1,
      aux_sym_pipe_chain_repeat1,
    ACTIONS(64), 2,
      anon_sym_voices,
      sym_identifier,
  [336] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(68), 2,
      anon_sym_RBRACE,
      anon_sym_PIPE,
    ACTIONS(70), 2,
      anon_sym_voices,
      sym_identifier,
  [351] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 2,
      anon_sym_voices,
      sym_identifier,
    ACTIONS(72), 3,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [364] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_RBRACE,
    ACTIONS(80), 1,
      anon_sym_PIPE,
    STATE(21), 1,
      aux_sym_pipe_chain_repeat1,
    ACTIONS(78), 2,
      anon_sym_voices,
      sym_identifier,
  [381] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_PIPE,
    ACTIONS(83), 1,
      anon_sym_RBRACE,
    STATE(18), 1,
      aux_sym_pipe_chain_repeat1,
    ACTIONS(85), 2,
      anon_sym_voices,
      sym_identifier,
  [398] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_RBRACE,
    ACTIONS(91), 1,
      anon_sym_legato,
    ACTIONS(89), 2,
      anon_sym_voices,
      sym_identifier,
  [412] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 2,
      anon_sym_RBRACE,
      anon_sym_PIPE,
    ACTIONS(70), 2,
      anon_sym_voices,
      sym_identifier,
  [424] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 2,
      anon_sym_RBRACE,
      anon_sym_PIPE,
    ACTIONS(78), 2,
      anon_sym_voices,
      sym_identifier,
  [436] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
    ACTIONS(95), 2,
      anon_sym_voices,
      sym_identifier,
  [448] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_EQ,
    ACTIONS(17), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [459] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      anon_sym_RBRACE,
    ACTIONS(101), 1,
      anon_sym_COMMA,
    STATE(37), 1,
      aux_sym_param_list_repeat1,
  [472] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    ACTIONS(33), 2,
      anon_sym_voices,
      sym_identifier,
  [483] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_RBRACE,
    ACTIONS(105), 2,
      anon_sym_voices,
      sym_identifier,
  [494] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      sym_identifier,
    STATE(22), 1,
      sym_node_call,
    STATE(57), 1,
      sym_pipe_chain,
  [507] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      anon_sym_RBRACE,
    ACTIONS(111), 2,
      anon_sym_voices,
      sym_identifier,
  [518] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      sym_identifier,
    STATE(24), 1,
      sym_node_call,
    STATE(25), 1,
      sym_pipe_segment,
  [531] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_RBRACE,
    ACTIONS(117), 2,
      anon_sym_voices,
      sym_identifier,
  [542] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 1,
      anon_sym_RBRACE,
    ACTIONS(121), 2,
      anon_sym_voices,
      sym_identifier,
  [553] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(26), 1,
      sym_primary,
    ACTIONS(39), 2,
      sym_identifier,
      sym_number,
  [564] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 1,
      anon_sym_RBRACE,
    ACTIONS(123), 1,
      anon_sym_COMMA,
    STATE(38), 1,
      aux_sym_param_list_repeat1,
  [577] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_RBRACE,
    ACTIONS(127), 1,
      anon_sym_COMMA,
    STATE(38), 1,
      aux_sym_param_list_repeat1,
  [590] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_mono,
    ACTIONS(132), 1,
      anon_sym_poly,
    STATE(30), 1,
      sym_voices_value,
  [603] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [611] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [619] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_patch,
    ACTIONS(140), 1,
      anon_sym_effect,
  [629] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 2,
      sym_identifier,
      sym_number,
  [637] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [645] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(146), 1,
      anon_sym_EQ,
  [655] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [663] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [671] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [679] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [687] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [695] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      sym_integer,
  [702] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      anon_sym_EQ,
  [709] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      anon_sym_RBRACE,
  [716] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      anon_sym_LBRACE,
  [723] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
  [730] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      ts_builtin_sym_end,
  [737] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_RBRACE,
  [744] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 1,
      anon_sym_LBRACE,
  [751] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 25,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 69,
  [SMALL_STATE(6)] = 94,
  [SMALL_STATE(7)] = 110,
  [SMALL_STATE(8)] = 130,
  [SMALL_STATE(9)] = 153,
  [SMALL_STATE(10)] = 176,
  [SMALL_STATE(11)] = 193,
  [SMALL_STATE(12)] = 211,
  [SMALL_STATE(13)] = 229,
  [SMALL_STATE(14)] = 249,
  [SMALL_STATE(15)] = 269,
  [SMALL_STATE(16)] = 289,
  [SMALL_STATE(17)] = 302,
  [SMALL_STATE(18)] = 319,
  [SMALL_STATE(19)] = 336,
  [SMALL_STATE(20)] = 351,
  [SMALL_STATE(21)] = 364,
  [SMALL_STATE(22)] = 381,
  [SMALL_STATE(23)] = 398,
  [SMALL_STATE(24)] = 412,
  [SMALL_STATE(25)] = 424,
  [SMALL_STATE(26)] = 436,
  [SMALL_STATE(27)] = 448,
  [SMALL_STATE(28)] = 459,
  [SMALL_STATE(29)] = 472,
  [SMALL_STATE(30)] = 483,
  [SMALL_STATE(31)] = 494,
  [SMALL_STATE(32)] = 507,
  [SMALL_STATE(33)] = 518,
  [SMALL_STATE(34)] = 531,
  [SMALL_STATE(35)] = 542,
  [SMALL_STATE(36)] = 553,
  [SMALL_STATE(37)] = 564,
  [SMALL_STATE(38)] = 577,
  [SMALL_STATE(39)] = 590,
  [SMALL_STATE(40)] = 603,
  [SMALL_STATE(41)] = 611,
  [SMALL_STATE(42)] = 619,
  [SMALL_STATE(43)] = 629,
  [SMALL_STATE(44)] = 637,
  [SMALL_STATE(45)] = 645,
  [SMALL_STATE(46)] = 655,
  [SMALL_STATE(47)] = 663,
  [SMALL_STATE(48)] = 671,
  [SMALL_STATE(49)] = 679,
  [SMALL_STATE(50)] = 687,
  [SMALL_STATE(51)] = 695,
  [SMALL_STATE(52)] = 702,
  [SMALL_STATE(53)] = 709,
  [SMALL_STATE(54)] = 716,
  [SMALL_STATE(55)] = 723,
  [SMALL_STATE(56)] = 730,
  [SMALL_STATE(57)] = 737,
  [SMALL_STATE(58)] = 744,
  [SMALL_STATE(59)] = 751,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primary, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_patch_decl_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_patch_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_patch_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_value, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_list, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_list, 3, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_call, 4, 0, 3),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node_call, 4, 0, 3),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipe_chain, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pipe_chain, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipe_segment, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pipe_segment, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_call, 3, 0, 3),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node_call, 3, 0, 3),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pipe_chain_repeat1, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pipe_chain_repeat1, 2, 0, 0),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pipe_chain_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipe_chain, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pipe_chain, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_voices_value, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_voices_value, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expr, 3, 0, 4),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expr, 3, 0, 4),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_list, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_voices_stmt, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_voices_stmt, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binding_stmt, 3, 0, 2),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binding_stmt, 3, 0, 2),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_patch_stmt, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_patch_stmt, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_voices_value, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_voices_value, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_param_list_repeat1, 2, 0, 0),
  [127] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_param_list_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_item, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binop, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_patch_decl, 6, 0, 1),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_patch_decl, 5, 0, 1),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_param, 3, 0, 5),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_effect_decl, 6, 0, 1),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [162] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_patchlang(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
